### ISSUE TITLE
Correct slither.config.json file

### ISSUE THREAD

**Issue by YourGuyD3v** [Cyfrin/6-thunder-loan-audit#3]
In `slither.config.json` file it should be `solc-version` instead of `incorrect-versions-of-solidity` because check on slither is `solc-version`

```diff
- "detectors_to_exclude": "conformance-to-solidity-naming-conventions,incorrect-versions-of-solidity",
+   "detectors_to_exclude": "conformance-to-solidity-naming-conventions,solc-version",
```

[slither.config.json file](https://github.com/Cyfrin/6-thunder-loan-audit/blob/5cf837b1f446a3c1dfdfce7860a173c8b10f6035/slither.config.json#L2C5-L2C105)
[Slither Docs](https://github.com/crytic/slither/wiki/Detector-Documentation#incorrect-versions-of-solidity)

**Comment by PatrickAlphaC** [comment]
fixed
